### ISSUE TITLE
List row actions and list placement in object details

### ISSUE THREAD

**Issue by itsptk** [rh-uxd/openshift-storybook#17]
Two List-related items that I thought the conventions could convey:

1. Row actions for items in the list should match the actions in the details view whenever possible (This is mentioned in the Lists page but I thought maybe one more sentence could be added to distinctly convey this.)
2. What circumstances a list of (sub)objects appears on the Overview tab in an objects details vs getting its own tab. My understanding is that if the object "owns" the sub-object it appears on Overview, vs if it's just a related object it can appear in its own tab. I thought this could be worth capturing if it hasn't been already.

**Comment by itsptk** [comment]
Duplicated in origin-design: https://github.com/openshift/openshift-origin-design/issues/318

**Comment by rachael-phillips** [comment]
Overview = details

**Comment by itsptk** [comment]
Closing as is now tracked in openshift/openshift-origin-design#318
