### ISSUE TITLE
Review Inline Edit Convention and pencil icon use

### ISSUE THREAD

**Issue by beanh66** [rh-uxd/openshift-storybook#19]
For fields with editing capability like annotations, we currently add the pencil icon to the right of the field value. We had discussed possibly moving the pencil to the field label rather than value, but this may interfere with the existing field label underline feature that displays field descriptions on click. 

We should come to an agreement on inline edit designs and update the conventions here as needed: http://openshift.github.io/openshift-origin-design/conventions/documentation/edit.html#edit-links

FYI @rachael-phillips @lizsurette @matthewcarleton @beaumorley

**Comment by andybraren** [comment]
+1, should we move this issue to the [OpenShift Design repo's issue tracker](https://github.com/openshift/openshift-origin-design/issues) with a `conventions` label?

**Comment by beanh66** [comment]
Doh! I knew I was doing something wrong :(

**Comment by beanh66** [comment]
Moved here: 

https://github.com/openshift/openshift-origin-design/issues/394
